[package]
name = "casper-client"
version = "2.0.0" # when updating, also update 'html_root_url' in lib.rs
authors = [
    "Marc Brinkmann <marc@casperlabs.io>",
    "Fraser Hutchison <fraser@casperlabs.io>",
]
edition = "2021"
description = "A client library and binary for interacting with the Casper network"
documentation = "https://docs.rs/casper-client"
readme = "README.md"
homepage = "https://casperlabs.io"
repository = "https://github.com/casper-ecosystem/casper-client-rs"
license = "Apache-2.0"

[lib]
crate-type = ["lib", "cdylib"]
name = "casper_client"
path = "lib/lib.rs"

[[bin]]
name = "casper-client"
path = "src/main.rs"
doc = false

[dependencies]
async-trait = "0.1.59"
base16 = "0.2.1"
base64 = "0.13.1"
casper-hashing = { version = "2.0.0", git = "https://github.com/gRoussac/casper-node/", default-features = false, branch = "casper-hashing-dev" }
casper-types = { version = "3.0.0" }
clap = { version = "4", features = [
    "cargo",
    "deprecated",
    "wrap_help",
], optional = true }
clap_complete = "4"
derp = "0.0.14"
ed25519-dalek = { version = "1", default-features = false }
getrandom = { version = "0.2.10", features = ["js"] }
hex-buffer-serde = "0.4.0"
humantime = "2"
itertools = "0.10.5"
jsonrpc-lite = "0.6.0"
k256 = { version = "0.7.3", features = [
    "arithmetic",
    "ecdsa",
    "sha256",
    "zeroize",
] }
num-traits = "0.2.15"
once_cell = "1"
pem = "1"
rand = "0.8.5"
reqwest = { version = "0.11.18", features = ["json"] }
schemars = "0.8"
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
signature = "1"
tempfile = "3"
thiserror = "=1.0.34"
tokio = { version = "1.23.0", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
], optional = true }
uint = "0.9.4"
untrusted = "0.9.0"

[features]
default = ["casper-types", "tokio", "clap", "casper-hashing"]
casper-types = ["casper-types/std"]
casper-hashing = ["casper-hashing/std"]
sdk = []

[build-dependencies]
vergen = { version = "7", default-features = false, features = ["git"] }

[package.metadata.deb]
features = ["vendored-openssl"]
revision = "0"
assets = [["./target/release/casper-client", "/usr/bin/casper-client", "755"]]
extended-description = """
Package for Casper Client to connect to Casper Node.

For information on using package, see https://github.com/CasperLabs/casper-node
"""

[package.metadata.deb.variants.bionic]
name = "casper-client"
revision = "0+bionic"

[package.metadata.deb.variants.focal]
name = "casper-client"
revision = "0+focal"

[package.metadata.rpm]
package = "casper-client"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
casper-client = { path = "/usr/bin/casper-client" }
